version: '3'

# ref https://qiita.com/asylum/items/17e655d8369c19affbc3
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGPASSWORD
      - POSTGRES_DB
      - TZ
    ports:
      - 15432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
